name: kakao_style_friend_feed
description: "kakao style friend feed by june"
#publish_to: 'none'
repository: https://github.com/juneview-songdo/kakao_style_friend_feed

version: 1.0.6

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  after_layout:
  bot_toast:
  device_preview:
  flutter:
    sdk: flutter
  flutter_screenutil:
  flutter_svg:
  flutter_zoom_drawer:
  gap:
  go_router:
  hive:
  isar_flutter_libs:
  june:
  june_flow_util:
  keyboard_attachable:
  modal_bottom_sheet:
  path_provider:
  styled_widget:

dev_dependencies:
  bot_toast_module:
  device_preview_module:
  flutter_lints:
  flutter_lints_module:
  flutter_test:
    sdk: flutter
  hive_module:
  june_view:  #@add
  june_view_more:  #@add
  screenutil_module:

flutter:
  assets:
    - assets/view/kakao_style_friend_feed/
  uses-material-design: true